import pandas as pd 
import re

media_url = {
        "New York": "New York",
        "york": "New York",
        "Brooklyn": "Brooklyn",
        "Adelaide": "Adelaide",
        "Alabama": "Alabama",
        "Albany": "Albany",
        "Albuquerque": "Albuquerque",
        "Alexandria": "Alexandria",
        "Amsterdam": "Amsterdam",
        "Ann Arbor": "Ann Arbor",
        "Arlington": "Arlington",
        "Atlanta": "Atlanta",
        "ATL": "Atlanta",
        "Austin": "Austin",
        "ATX": "Austin",
        
        "Baghdad": "Baghdad",
        "Baltimore": "Baltimore",
        "Bangalore": "Bangalore",
        "Bangkok": "Bangkok ",
        "Bay Area": "Bay Area",
        "SF": "Bay Area",
        "S.F.": "Bay Area",
        "San Francisco": "Bay Area",
        "San Jose": "Bay Area",
        "Berkeley": "Easy Bay",
        "Oakland": "East Bay",
        "Boston": "Boston",
        "Berlin": "Berlin",
        "Beverly Hills": "LA",
        "Bogota": "Bogota",
        "Boulder": "Boulder",
        "Brighton": "Brighton",
        "Brisbane": "Brisbane",
        "Bristol": "Bristol",
        "Bronx": "New York",
        "Brussels" : "Brussels",
        "Chicago": "Chicago",
        "Cleveland": "Cleveland",
        "D.C.": "Washington",
        "DC": "Washington",
        "Dallas": "Dallas",
        "Denver": "Denver",
        "Dublin": "Dublin",
        "East Bay": "East Bay",
        "Edinburgh": "Edinburgh",
        "Hollywood": "LA",
        "Hong Kong": "Hong Kong",
        "Hong Kong": "Houston",
        "Istanbul": "Istanbul",
        "Jersey": "New Jersey",
        "Johannesburg": "Johannesburg",
        "Kabul": "Kabul",
        "L.A": "LA",
        "Liverpool": "Livverpool",
        "Los Angeles": "LA",
        "Madrid": "Madrid",
        "Manchester": "Manchester",
        "Manhattan": "New York",
        "Massachusetts": "Massachusetts",
        "Melbourne": "Melbourne",
        "Mexico City": "Mexico City",
        "Miami": "Miami",
        "Minneapolis": "Minneapolis",
        "Montreal" : "Montreal",
        "Moscow": "Moscow",
        "Nashville": "Nashville",
        "Nairobi": "Nairobi",
        "New Delhi": "New Delhi",
        "New  York": "New York",
        "New Jersey": "New Jersey",
        "New Orleans": "New Orleans",
        "Newark": "New Jersey",
        "Oakland": "East Bay",
        "Ottawa": "Ottawa",
        "Paris": "Paris",
        "Philadelphia": "Philadelphia",
        "Phoenix": "Phoenix",
        "Pittsburgh": "Pittsburgh",
        "Portland": "Portland",
        "Queens": "New York",
        "Roma": "Rome",
        "Rome": "Rome",
        "Sacramento": "Sacramento",
        "San Antonio": "San Antonio",
        "San Diego": "San Diego",
        "Santa Monica": "LA",
        "scotland": "scotland",
        "Seattle": "Seattle",
        "Seoul": "Seoul",
        "Silicon Valley": "Bay Area",
        "Singapore": "Singapore",
        "Sydney": "Sydney",
        "Taipei": "Taipei",
        "Texas": "Texas",
        "TX": "Texas",
        "Tokyo": "Tokyo",
        "Toronto": "Toronto",
        "UK": "UK",
        "United Kingdom": "UK",
        "United States": "USA",
        "USA": "USA",
        "Vancouver": "Vancouver",
        "Williamsburg": "Brooklyn",       
        "Beijing": "Beijing",
        "Beirut": "Beirut",        
        "Belfast": "Belfast",
        "Australia": "Australia",
        "America": "America",
        "California": "California",
        "Canada": "Canada",
        "Connecticut": "Connecticut",
        "England": "UK",
        "UK": "UK",
        "Europe": "Europe",
        "Florida": "Florida",
        "France": "France",
        "Glasgow": "Glasgow",
        "Ireland": "Ireland",
        "LA": "LA",
        "NY": "New York",
        "VA": "Virginia",
        "Virginia": "Virginia",
        "RI": "Rhode Island"   
}

def f(row):
    #print(row)
    for key in media_url.keys():
        key_search = key.lower()
        row['location'] = str(row['location']).lower()
        #print(row['url'])
        m = re.search(key_search, row['location'])
        if m is not None:
            return media_url[key]
    return row['location']



media_data = pd.read_csv("Top10000Journos.csv", lineterminator='\n', encoding ='utf-8')


media_data["broad_location"] = media_data.apply(f, axis=1)


media_data.to_csv(path_or_buf="top_temp.csv", index = False)
